/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const VoiceLog = IDL.Record({
  'userInput' : IDL.Text,
  'assistantResponse' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Preferences = IDL.Record({
  'mode' : IDL.Text,
  'speechRate' : IDL.Nat,
  'haptics' : IDL.Bool,
  'language' : IDL.Text,
  'wakeWord' : IDL.Text,
  'highContrast' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func([Task], [IDL.Nat], []),
  'addVoiceLog' : IDL.Func([VoiceLog], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getPreferences' : IDL.Func([IDL.Principal], [Preferences], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTasksByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksByCompletion' : IDL.Func([IDL.Bool], [IDL.Vec(Task)], ['query']),
  'getVoiceLogs' : IDL.Func([IDL.Principal], [IDL.Vec(VoiceLog)], ['query']),
  'setPreferences' : IDL.Func([Preferences], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const VoiceLog = IDL.Record({
    'userInput' : IDL.Text,
    'assistantResponse' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Preferences = IDL.Record({
    'mode' : IDL.Text,
    'speechRate' : IDL.Nat,
    'haptics' : IDL.Bool,
    'language' : IDL.Text,
    'wakeWord' : IDL.Text,
    'highContrast' : IDL.Bool,
  });
  
  return IDL.Service({
    'addTask' : IDL.Func([Task], [IDL.Nat], []),
    'addVoiceLog' : IDL.Func([VoiceLog], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getPreferences' : IDL.Func([IDL.Principal], [Preferences], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTasksByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksByCompletion' : IDL.Func([IDL.Bool], [IDL.Vec(Task)], ['query']),
    'getVoiceLogs' : IDL.Func([IDL.Principal], [IDL.Vec(VoiceLog)], ['query']),
    'setPreferences' : IDL.Func([Preferences], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };