/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Preferences {
  'mode' : string,
  'speechRate' : bigint,
  'haptics' : boolean,
  'language' : string,
  'wakeWord' : string,
  'highContrast' : boolean,
}
export interface Task {
  'title' : string,
  'completed' : boolean,
  'dueDate' : bigint,
  'description' : string,
  'category' : string,
}
export interface TaskWithId {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'dueDate' : bigint,
  'description' : string,
  'category' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface VoiceLog {
  'userInput' : string,
  'assistantResponse' : string,
  'timestamp' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  /**
   * / ***********
   * / ***********
   */
  'addTask' : ActorMethod<[Task], bigint>,
  'addVoiceLog' : ActorMethod<[VoiceLog], undefined>,
  'chatWithAI' : ActorMethod<[string], string>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAIProvider' : ActorMethod<[], string>,
  'getAllTasks' : ActorMethod<[], Array<TaskWithId>>,
  'getPreferences' : ActorMethod<[Principal], Preferences>,
  'getTask' : ActorMethod<[bigint], TaskWithId>,
  'getTasksByCategory' : ActorMethod<[string], Array<TaskWithId>>,
  'getTasksByCompletion' : ActorMethod<[boolean], Array<TaskWithId>>,
  'getVoiceLogs' : ActorMethod<[Principal], Array<VoiceLog>>,
  'hasOpenAIKey' : ActorMethod<[], boolean>,
  'setAIConfig' : ActorMethod<[string, string], undefined>,
  /**
   * / ***********
   * / ***********
   */
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'setPreferences' : ActorMethod<[Preferences], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];