/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const TaskWithId = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const VoiceLog = IDL.Record({
  'userInput' : IDL.Text,
  'assistantResponse' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Preferences = IDL.Record({
  'mode' : IDL.Text,
  'speechRate' : IDL.Nat,
  'haptics' : IDL.Bool,
  'language' : IDL.Text,
  'wakeWord' : IDL.Text,
  'highContrast' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func([Task], [IDL.Nat], []),
  'addVoiceLog' : IDL.Func([VoiceLog], [], []),
  'chatWithAI' : IDL.Func([IDL.Text], [IDL.Text], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(TaskWithId)], ['query']),
  'getAIProvider' : IDL.Func([], [IDL.Text], ['query']),
  'getPreferences' : IDL.Func([IDL.Principal], [Preferences], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [TaskWithId], ['query']),
  'getTasksByCategory' : IDL.Func([IDL.Text], [IDL.Vec(TaskWithId)], ['query']),
  'getTasksByCompletion' : IDL.Func([IDL.Bool], [IDL.Vec(TaskWithId)], ['query']),
  'getVoiceLogs' : IDL.Func([IDL.Principal], [IDL.Vec(VoiceLog)], ['query']),
  'hasOpenAIKey' : IDL.Func([], [IDL.Bool], ['query']),
  'setAIConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'setPreferences' : IDL.Func([Preferences], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const TaskWithId = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const VoiceLog = IDL.Record({
    'userInput' : IDL.Text,
    'assistantResponse' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Preferences = IDL.Record({
    'mode' : IDL.Text,
    'speechRate' : IDL.Nat,
    'haptics' : IDL.Bool,
    'language' : IDL.Text,
    'wakeWord' : IDL.Text,
    'highContrast' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addTask' : IDL.Func([Task], [IDL.Nat], []),
    'addVoiceLog' : IDL.Func([VoiceLog], [], []),
    'chatWithAI' : IDL.Func([IDL.Text], [IDL.Text], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(TaskWithId)], ['query']),
    'getAIProvider' : IDL.Func([], [IDL.Text], ['query']),
    'getPreferences' : IDL.Func([IDL.Principal], [Preferences], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [TaskWithId], ['query']),
    'getTasksByCategory' : IDL.Func([IDL.Text], [IDL.Vec(TaskWithId)], ['query']),
    'getTasksByCompletion' : IDL.Func([IDL.Bool], [IDL.Vec(TaskWithId)], ['query']),
    'getVoiceLogs' : IDL.Func([IDL.Principal], [IDL.Vec(VoiceLog)], ['query']),
    'hasOpenAIKey' : IDL.Func([], [IDL.Bool], ['query']),
    'setAIConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'setPreferences' : IDL.Func([Preferences], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };