/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Preferences {
    mode: string;
    speechRate: bigint;
    haptics: boolean;
    language: string;
    wakeWord: string;
    highContrast: boolean;
}
export interface Task {
    title: string;
    completed: boolean;
    dueDate: bigint;
    description: string;
    category: string;
}
export interface TaskWithId {
    id: bigint;
    title: string;
    completed: boolean;
    dueDate: bigint;
    description: string;
    category: string;
}
export interface VoiceLog {
    userInput: string;
    assistantResponse: string;
    timestamp: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    /**
     * / ***********
     * / ***********
     */
    addTask(task: Task): Promise<bigint>;
    addVoiceLog(log: VoiceLog): Promise<void>;
    chatWithAI(message: string): Promise<string>;
    completeTask(taskId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    getAllTasks(): Promise<Array<TaskWithId>>;
    getPreferences(user: Principal): Promise<Preferences>;
    getTask(taskId: bigint): Promise<TaskWithId>;
    getTasksByCategory(category: string): Promise<Array<TaskWithId>>;
    getTasksByCompletion(completed: boolean): Promise<Array<TaskWithId>>;
    getVoiceLogs(user: Principal): Promise<Array<VoiceLog>>;
    hasOpenAIKey(): Promise<boolean>;
    /**
     * / ***********
     * / ***********
     */
    setOpenAIKey(key: string): Promise<void>;
    setPreferences(prefs: Preferences): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateTask(taskId: bigint, task: Task): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTask(arg0: Task): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0);
            return result;
        }
    }
    async addVoiceLog(arg0: VoiceLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVoiceLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVoiceLog(arg0);
            return result;
        }
    }
    async chatWithAI(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.chatWithAI(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatWithAI(arg0);
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllTasks(): Promise<Array<TaskWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return result;
        }
    }
    async getPreferences(arg0: Principal): Promise<Preferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences(arg0);
            return result;
        }
    }
    async getTask(arg0: bigint): Promise<TaskWithId> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return result;
        }
    }
    async getTasksByCategory(arg0: string): Promise<Array<TaskWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByCategory(arg0);
            return result;
        }
    }
    async getTasksByCompletion(arg0: boolean): Promise<Array<TaskWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByCompletion(arg0);
            return result;
        }
    }
    async getVoiceLogs(arg0: Principal): Promise<Array<VoiceLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceLogs(arg0);
            return result;
        }
    }
    async hasOpenAIKey(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasOpenAIKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasOpenAIKey();
            return result;
        }
    }
    async setOpenAIKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIKey(arg0);
            return result;
        }
    }
    async setPreferences(arg0: Preferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPreferences(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
